[project]
name = "access-controller"
description = "Minimal access control contract"
authors = ["local"]
telemetry = false

[contracts.access-controller]
path = "contracts/access-controller.clar"

[repl]
costs_version = 3
